import { test, expect } from '@playwright/test';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';

test('desktop board, filters, modal keyboard behavior, and mobile layout',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Make the Quran reachable.'})).toBeVisible();
  await expect(page.locator('.request-card').first()).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('desktop.png'),fullPage:true});
  await page.getByLabel('Filter by language').selectOption('French');
  for(const card of await page.locator('.request-card').all()) await expect(card).toContainText('French');
  await page.getByLabel('Search requests').fill('unfindable-request-xyz');
  await expect(page.getByRole('heading',{name:'No requests match just yet.'})).toBeVisible();
  await page.getByRole('button',{name:'Reset filters'}).click();
  await page.getByRole('button',{name:'How it works',exact:true}).first().click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:testInfo.outputPath('mobile.png'),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:/Accessible library/}).click();
  await expect(page.getByRole('heading',{name:'Quran translations, open to everyone.'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('register, request, upload, independent review, and public playback',async({page,browser,playwright})=>{
  const stamp=Date.now();
  const email=`volunteer-${stamp}@test.example`,reviewerEmail=`reviewer-${stamp}@test.example`;
  const title=`Al-Baqarah translation reading ${stamp}`;
  const db=new DatabaseSync(path.join(process.cwd(),'.test-data','browser','charity.sqlite'));
  const used=new Set((db.prepare("SELECT source_url FROM requests WHERE source_kind='quran'").all() as {source_url:string}[]).map(r=>r.source_url));
  db.close();
  const aya=Array.from({length:286},(_,i)=>i+1).find(n=>!used.has(`https://quranenc.com/en/browse/english_rwwad/2#${n}`))!;
  await page.goto('/');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('button',{name:'New here? Create an account'}).click();
  await page.getByLabel('Your name').fill('Test Volunteer');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password',{exact:true}).fill('test-only-password-2026');
  await page.getByRole('button',{name:'Create my account'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Create a request'}).click();
  await page.getByLabel('Give your request a title').fill(title);
  await page.getByLabel('Who would an audio version help?').fill('A practice request to verify accessible audio publishing from start to finish.');
  await expect(page.getByLabel('Quran translation')).toBeEnabled({timeout:15000});
  await page.getByLabel('Quran translation').selectOption('english_rwwad');
  await page.getByLabel('Surah',{exact:true}).fill('2');
  await page.getByLabel('Verse',{exact:true}).fill(String(aya));
  await page.getByRole('button',{name:'Preview Quran verse'}).click();
  await expect(page.locator('.quran-preview .quran-arabic')).toHaveText(/[\u0600-\u06ff]/,{timeout:15000});
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Publish request'}).click();
  await expect(page.getByRole('dialog').getByRole('heading',{name:title,exact:true})).toBeVisible();
  const invalid=Buffer.from('This is not an audio recording.');
  const row=(await (await page.request.get('/api/requests')).json()).requests.find((r:{title:string})=>r.title===title);
  expect(row.source_kind).toBe('quran');
  expect(row.language).toBe('English');
  expect(row.source_arabic).toMatch(/[\u0600-\u06ff]/);
  const unrelated=await page.request.post('/api/requests',{data:{source_kind:'community'}});
  expect(unrelated.status()).toBe(400);
  const duplicate=await page.request.post('/api/requests',{data:{source_kind:'quran',translation:'english_rwwad',sura:2,aya,title,description:'The same sourced verse in the same translation.',permission:true,language:'French',source_text:'Untrusted replacement'}});
  expect((await duplicate.json()).id).toBe(row.id);
  const bad=await page.request.post('/api/contributions',{multipart:{request_id:row.id,permission:'true',audio:{name:'fake.mp3',mimeType:'audio/mpeg',buffer:invalid}}});
  expect(bad.status()).toBe(400);
  await page.getByRole('button',{name:'Start recording',exact:true}).click();
  await expect(page.getByRole('button',{name:'Stop · 0:01',exact:true})).toBeVisible();
  await page.getByRole('button',{name:/Stop ·/}).click();
  await expect(page.locator('.audio-preview audio')).toHaveAttribute('src',/^blob:/);
  const wav=Buffer.alloc(16044);wav.write('RIFF',0);wav.writeUInt32LE(16036,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(16000,40);
  await page.locator('input[type=file]').setInputFiles({name:'test-recording.wav',mimeType:'audio/wav',buffer:wav});
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Submit for review'}).click();
  await expect(page.getByText('A different community reviewer will check your recording.')).toBeVisible();
  const details=await (await page.request.get(`/api/requests/${row.id}`)).json();
  const audioId=details.contributions[0].id;
  const anonymous=await playwright.request.newContext({baseURL:'http://127.0.0.1:3100'});
  expect((await anonymous.get(`/api/audio/${audioId}`)).status()).toBe(403);
  expect((await page.request.post(`/api/contributions/${audioId}`,{data:{decision:'approved',checked:true}})).status()).toBe(403);
  const reviewerContext=await browser.newContext({baseURL:'http://127.0.0.1:3100'});
  const registration=await reviewerContext.request.post('/api/auth',{data:{action:'register',name:'Test Reviewer',email:reviewerEmail,password:'test-only-password-2026'}});
  expect(registration.ok()).toBe(true);
  const database=new DatabaseSync(path.join(process.cwd(),'.test-data','browser','charity.sqlite'));
  database.prepare("UPDATE users SET role='reviewer' WHERE email=?").run(reviewerEmail);database.close();
  const reviewPage=await reviewerContext.newPage();await reviewPage.goto('/');
  await reviewPage.getByRole('button',{name:/Review queue/}).click();
  await reviewPage.getByRole('button').filter({has:reviewPage.getByRole('heading',{name:title})}).click();
  await expect(reviewPage.locator('.recording-item audio')).toBeVisible();
  await reviewPage.getByRole('checkbox').check();
  await reviewPage.getByRole('button',{name:'Approve & publish'}).click();
  await expect(reviewPage.getByText('Published',{exact:true})).toBeVisible();
  const published=await anonymous.get(`/api/audio/${audioId}`);expect(published.status()).toBe(200);expect(published.headers()['content-type']).toBe('audio/wav');
  const range=await anonymous.get(`/api/audio/${audioId}`,{headers:{Range:'bytes=0-43'}});expect(range.status()).toBe(206);expect((await range.body()).length).toBe(44);
  await reviewPage.getByRole('button',{name:'Close dialog'}).click();
  await reviewPage.getByRole('button',{name:/Accessible library/}).click();
  await expect(reviewPage.getByRole('heading',{name:title})).toBeVisible();
  await anonymous.dispose();await reviewerContext.close();
});
